base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('pik/<int:pk>', views.pikDetail, name='detail'),
    path('pik/<int:pik>/update', views.updatePik, name='updatePik'),   
    path('pik/<int:pik>/k-0', views.tambahKNol, name='KNol'),
    path('pik/<int:pik>/anggota', views.listAnggota, name='anggota'),
    path('pik/<int:pik>/anggota/<int:pk>/update', views.updateAnggota, name='updateAnggota'),
    path('pik/<int:pik>/laporan/baru', views.tambahLaporan, name='tambahLaporan'),
    path('pik/<int:pik>/anggota/baru', views.tambahAnggota, name='tambahAnggota'),
    
    path('listPik/', views.listPik, name='listPik'),
    path('pik/<int:pik>/laporan/cetak', views.viewLaporanPik, name='laporanPik'),
    
    path('login/', views.loginView, name='login'),
    path('logout/', views.user_logOut, name='logout'),
]

pikR/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
JENIS_KELAMIN = (
        ("1",'Laki-laki'), 
        ("2",'Perempuan')
        )

class PikR(models.Model):
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    nama = models.CharField(max_length=50)
    deskripsi = models.TextField(null = True, blank = True)
    fileK0 = models.FileField(upload_to = 'k0/', null = True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)
    
    def __str__(self):
        return self.nama


class Pengurus(models.Model):
    nama = models.CharField(max_length=50)
    jenisKelamin = models.CharField(max_length=50)
    alamat = models.TextField()
    pik = models.ForeignKey(PikR, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return self.nama
 
class Anggota(models.Model):
    nama = models.CharField(max_length=50)
    jenisKelamin = models.CharField(max_length=1, choices=JENIS_KELAMIN, default='1')
    jabatan = models.CharField(max_length=50, default = 'Anggota')
    pik = models.ForeignKey(PikR, on_delete=models.CASCADE)
    def __str__(self):
        return self.nama
    
class LaporanKegiatan(models.Model):
    pik = models.ForeignKey(PikR, on_delete=models.CASCADE, null=False, blank=False)
    judul = models.CharField(max_length = 100)
    deskripsi = models.TextField(null=True)
    tanggal = models.DateField()
    gambar = models.ImageField(null=True, blank=True, upload_to='laporan/')
    
    created = models.DateTimeField(auto_now_add=True, null = True)
    updated = models.DateTimeField(auto_now = True)
    def __str__(self):
        return self.judul
    
    class Meta:
        ordering = ['-created']

base/forms.py
from django.forms import ModelForm
from django import forms
from .models import PikR, LaporanKegiatan, Anggota

from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper

class PikForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Submit'))
    
    class Meta:
        model = PikR
        fields = ['nama', 'deskripsi']
        widgets = {
            'deskripsi': forms.Textarea(
            )
        }
    

class KNolForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Submit'))
    
    class Meta:
        model = PikR
        fields = ['fileK0']   

class LaporanPikForm(ModelForm):
     
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Submit'))   
          
    class Meta:
        model = LaporanKegiatan
        fields = '__all__'
        exclude = ['pik']
        widgets = {
            'tanggal': forms.DateTimeInput(
                attrs={
                    'type' : 'date'
                }
            ),
            'deskripsi': forms.Textarea(
            )
        }

class AnggotaPikForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Submit'))   
    
    class Meta:
        model = Anggota
        fields = '__all__'
        exclude = ['pik']

base/views.py
from django.shortcuts import redirect, render
from .models import PikR, Pengurus, LaporanKegiatan, Anggota, User
from .forms import LaporanPikForm, AnggotaPikForm, KNolForm, PikForm
from django.contrib import messages
# Create your views here

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def loginView(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        print(request.POST)
        usernameIn = request.POST['username']
        passwordIn = request.POST['password']
        
        user = authenticate(request, username = usernameIn, password=passwordIn)
        if user != None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Username or Password anda Salah!')
       
    return render(request, 'base/login.html')

def user_logOut(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('login')
    
    return redirect('home')

@login_required(login_url='login/')
def index(request):
    try:
        modelsPik = PikR.objects.get(admin = request.user)
    except:
        modelsPik = PikR.objects.none()
    
    allPik = PikR.objects.all()
    if request.user.is_superuser:
        allKegiatan = LaporanKegiatan.objects.all()
    else:
        allKegiatan = LaporanKegiatan.objects.filter(pik = modelsPik)
    print(allPik)
    
    context= {
        'pik': modelsPik,
        'allPik': allPik,
        'kegiatan': allKegiatan
    }
    return render(request, 'base/index.html', context)

@login_required(login_url='login/')
def pikDetail(request, pk):
    modelsPik = PikR.objects.get(id=pk)
    
    print(modelsPik.admin)
    kegiatan = modelsPik.laporankegiatan_set.all()
    anggota = modelsPik.anggota_set.all()
    print(kegiatan)
    context = {
        'pik': modelsPik,
        'kegiatan' : kegiatan,
        'anggota' : anggota
    } 
    return render(request, 'base/detail.html', context)

@login_required(login_url='login/')
def updatePik(request, pik):
    modelsPik = PikR.objects.get(id=pik)
    if request.user != modelsPik.admin:
        return redirect('home')
    form = PikForm(instance = modelsPik)
    if request.method == 'POST':
        form = PikForm(request.POST, instance = modelsPik)
        if form.is_valid():
            form.save()
            messages.success(request, f'Pik {modelsPik.nama} Berhasil Diupdate')
            return redirect('detail', pik)
    context = {
        'pik': modelsPik,
        'form' : form
    }
    return render(request, 'base/updatePik.html', context)
    
            
@login_required(login_url='login/')
def tambahLaporan(request, pik):
    modelsPik = PikR.objects.get(id=pik)
    if request.user != modelsPik.admin:
        return redirect('home')
    form = LaporanPikForm()
    if request.method == 'POST':
        form = LaporanPikForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.pik = modelsPik
            instance.save()
            messages.success(request, 'Laporan Berhasil Ditambahkan')
            return redirect('detail', pik)
    
    context = {
        'pik': modelsPik,
        'form' : form
    }
    return render(request, 'base/input_laporan.html', context)

@login_required(login_url='login/')
def tambahAnggota(request, pik):
    modelsPik = PikR.objects.get(id=pik)
    if request.user != modelsPik.admin:
        return redirect('home')
    form = AnggotaPikForm()
    if request.method == 'POST':
        form = AnggotaPikForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.pik = modelsPik
            instance.save()
            messages.success(request, 'Anggota Berhasil Ditambahkan')
            return redirect('detail', pik) 
    context = {
        'pik': modelsPik,
        'form' : form
    }
    return render(request, 'base/input_laporan.html', context)



@login_required(login_url='login/')
def tambahKNol(request, pik):
    modelsPik = PikR.objects.get(id=pik)
    if request.user != modelsPik.admin:
        return redirect('home')
    form = KNolForm(instance = modelsPik)
    if request.method == 'POST':
        form = KNolForm(request.POST, request.FILES, instance=modelsPik)
        if form.is_valid():
            form.save()
            
            messages.success(request, 'K-0 Berhasil Ditambahkan')
            return redirect('detail', pik) 
        
    context = {
        'pik': modelsPik,
        'form' : form
    }
    return render(request, 'base/input_K0.html', context)

@login_required(login_url='login/')
def listAnggota(request, pik):
    modelsPik = PikR.objects.get(id=pik)
    anggota = modelsPik.anggota_set.all()
    if request.method == 'POST':
        try:
            instance = Anggota.objects.get(id =request.POST['delete'])
            instance.delete()
            messages.success(request, 'Anggota Berhasil Dihapus')
        except:
            return redirect('anggota', pik)
        
    context = {
        'pik': modelsPik,
        'anggota': anggota
    }
    return render(request, 'base/list_anggota.html', context)

@login_required(login_url='login/')
def updateAnggota(request, pik, pk):
    modelsPik = PikR.objects.get(id=pik)
    if request.user != modelsPik.admin:
        return redirect('home')
    
    anggota = modelsPik.anggota_set.get(id=pk)
    
    form = AnggotaPikForm(instance=anggota)
    if request.method == 'POST':
        form = AnggotaPikForm(request.POST, instance=anggota)
        if form.is_valid():
            form.save()
            messages.success(request, 'Anggota Berhasil Diupdate')
            return redirect('anggota', pik) 
    context = {
        'anggota': anggota,
        'pik': modelsPik,
        'form' : form
    }
    return render(request, 'base/update_anggota.html', context)

@login_required(login_url='login/')
def listPik(request):
    modelsPik = PikR.objects.all()
    
    context = {
        'listPik': modelsPik
    }
    return render(request, 'base/list_pik.html', context)

@login_required(login_url='login/')
def viewLaporanPik(request, pik):
    modelsPik =PikR.objects.get(id=pik)
    laporanPik = modelsPik.laporankegiatan_set.all()
    context = {
        'pik': modelsPik,
        'kegiatan': laporanPik
    }
    
    return render(request, 'base/laporanPik.html', context)

base/templates/base/detail.html
{% extends 'base.html' %}
{% load static %}
{% block pageHead %}{{pik.nama}}{% endblock pageHead %}
{% block page %}{{pik.nama}}{% endblock page %}

{% block content %}
<!-- Default box -->
<div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
          <div class="row">
            <div class="col-12 col-sm-6">
                <a href="{% url 'anggota' pik.id %}">
                <div class="info-box bg-primary">
                  <div class="info-box-content">
                    <span class="info-box-text text-center"><h5>Anggota PIK</h5></span>
                    <span class="info-box-number text-center mb-0 text-warning"><h4>{{anggota.count}}</h4></span>
                  </div>
                </div>
              </a>
            </div>
            
            <div class="col-12 col-sm-6">
                <a href="">
                <div class="info-box bg-primary">
                  <div class="info-box-content">
                    <span class="info-box-text text-center "><h5>Kegiatan</h5></span>
                    <span class="info-box-number text-center  mb-0 text-warning"><h4>{{kegiatan.count}}</h4></span>
                  </div>
                </div>
              </a>
            </div>
           
          </div>
          <div class="row">
            <div class="col-12">
              <h4>Kegiatan Terakhir</h4>
              <hr>
                {% if kegiatan %}
                    {% for kegiatan in kegiatan %}
                    <div class="post">
                        <div class="user-block">
                        
                            <span class="username">
                                <h3 class="text-primary">{{kegiatan.judul}}</h3>
                            </span>
                            <span class="description">{{kegiatan.tanggal}}</span>
                        </div>
                        <!-- /.user-block -->
                        
                        {{kegiatan.deskripsi | safe}}
                       
                        {% if kegiatan.gambar %}
                        <div class="gambar-kegiatan">
                          <img src="{{kegiatan.gambar.url}}" alt="Product Image">
                        </div>
                        {% endif %}
                                                     
   
                    </div>
                    {% endfor %}
                {% else %}
                <h3>Belum ada kegiatan pada PIK ini</h3>
                {% endif %}
                
            </div>
          </div>
        </div>
        <div class="col-12 col-md-12 col-lg-4 pt-3 order-1 order-md-2 pik-info">
          {% if request.user == pik.admin %}
          <a href="{% url 'updatePik' pik.id %}"><h3 class="text-primary"><i class="fas fa-paint-brush"></i>{{pik.nama}}</h3></a>
          {% else %}
          <h3 class="text-primary"><i class="fas fa-paint-brush"></i>{{pik.nama}}</h3>
          {% endif %}
          <p class="text-muted">
            {% if pik.deskripsi %}
              {{pik.deskripsi|safe }}
              {% else %}

              Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terr.</p>
            {% endif %}
          <br>
          <div class="text-muted">
            
            <p class="text-sm">Pengurus
              <b class="d-block">{{pik.admin.first_name}} {{pik.admin.last_name}}</b>
            </p>
          </div>

          <h5 class="mt-5 text-muted">File K0</h5>
          <ul class="list-unstyled">
            {% if pik.fileK0 %}
            <li>
              <a href="{{pik.fileK0.url}}" class="btn-link text-secondary"><i class="far fa-fw fa-file-pdf"></i>{{pik.fileK0.name}}</a>
            </li>
            {% else %}
            <li>
              <a>Belum Ada File K0</a>
            </li>
            {% endif %}
            
          </ul>
          <div class="text-center mt-5 mb-3 gap-3">
            {% if request.user.is_authenticated %}
              {% if request.user.is_superuser %}
                {% if request.user == pik.admin  %}
                  <a href="{% url 'tambahLaporan' pik.id %}" class="btn btn-sm btn-primary">Tambah Laporan Kegiatan</a>
                  <a href="{% url 'tambahAnggota' pik.id %}" class="btn btn-sm btn-warning">Tambah Data Anggota</a>
                  <a href="{% url 'KNol' pik.id %}" class="btn btn-sm btn-success">Tambah File k0</a>
                {% else %}
                  <a href="{% url 'laporanPik' pik.id %}" class="btn btn-sm btn-primary">Lihat Laporan Kegiatan</a>
                {% endif %}
              {% elif request.user == pik.admin %}
                <a href="{% url 'tambahLaporan' pik.id %}" class="btn btn-sm btn-primary">Tambah Laporan Kegiatan</a>
                <a href="{% url 'laporanPik' pik.id %}" class="btn btn-sm btn-primary">Lihat Laporan Kegiatan</a>
                <a href="{% url 'tambahAnggota' pik.id %}" class="btn btn-sm btn-warning">Tambah Data Anggota</a>

                <a href="{% url 'KNol' pik.id %}" class="btn btn-sm btn-success">Tambah File k0</a>
              {% endif %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
<style>
 
  .pik-info {
    box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
    height: fit-content;
  }

  .pik-info iframe {
    width: 100%;
    height: 300px;
}
</style>
{% endblock content %}

base/templates/base/index.html
{% extends 'base.html' %}
{% block pageHead %}Dashboard{% endblock pageHead %}
{% block page %}Dashboard{% endblock page %}
{% block content %}
{% load static %}
<div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      {% if pik %}
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-info">
          <div class="inner">
            <h3>{{pik.nama}}</h3>

            <p>PIK Saya</p>
          </div>
          <div class="icon">
            <i class="ion ion-home"></i>
          </div>
          <a href="{% url 'detail' pik.id %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      {% endif %}
      
      {% if request.user.is_superuser %}
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
          <div class="inner">
            <h3>{{allPik.count}}</h3>

            <p>Semua PIK</p>
          </div>
          <div class="icon">
            <i class="ion ion-stats-bars"></i>
          </div>
          <a href="{% url 'listPik' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>
      {% endif %}
      <!-- ./col -->
      
    </div>
    <div class="row">
      <div class="col-md-12">
        <!-- The time line -->
        <div class="timeline">
          <!-- timeline time label -->
          <div class="time-label">
            <span class="bg-info">Aktivitas Terbaru</span>
          </div>
          <!-- /.timeline-label -->
          <!-- timeline item -->
          {% for k in kegiatan %}
            
            <div>
              <i class="fas fa-clock bg-blue"></i>
              <div class="timeline-item">
                <span class="time"><i class="fas fa-clock"></i> {{k.created|timesince}}</span>
                <h3 class="timeline-header"><a href="#">{{k.pik}}</a> Menambahkan Kegiatan {{k.judul}}</h3>

                <div class="timeline-body">
                      {% if k.gambar %}
                      <div class="gambar-kegiatan">
                        <img src="{{k.gambar.url}}" alt="Product Image">
                      </div>
                      {% endif %}
                  
                      {{k.deskripsi|safe}}

                      
                
                </div>
                <div class="timeline-footer">
                  <p class="text-muted">Tanggal Kegiatan {{k.tanggal}}</p>
                </div>
              </div>
            </div> 
          {% endfor %}
          
          <!-- END timeline item -->
          <div>
            <i class="fas fa-clock bg-gray"></i>
          </div>
        </div>
      </div>
      <!-- /.col -->
    </div>
  </div>
  </div><!-- /.container-fluid -->

<style>
  .timeline-body p {
    max-width: 100%;
    overflow:hidden;
  }
  .timeline-body p img {
   
    width: 100%;
   
    overflow:hidden;
    max-height: 600px;
    height:auto;
  }
</style>

{% endblock content %}

base/templates/base/input_K0.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block pageHead %}K0 {{pik.nama}}{% endblock pageHead %}
{% block page %}K0 {{pik.nama}}{% endblock page %}
{% block content %}
<div class="container-fluid">
    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Tambah K0 <strong>{{pik.nama}}</strong></h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="POST" enctype="multipart/form-data">
          <div class="card-body">
            {% csrf_token %}
            {% crispy form%}
          </div>
          <!-- /.card-body -->

        </form>
    </div>
</div>

{% endblock content %}

base/templates/base/input_laporan.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block pageHead %}Tambah Laporan {{pik.nama}}{% endblock pageHead %}
{% block page %}Tambah Laporan {{pik.nama}}{% endblock page %}
{% block content %}
<div class="container-fluid">
    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Tambah Laporan Baru <strong>{{pik.nama}}</strong></h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="POST" enctype="multipart/form-data">
          <div class="card-body">
            {% csrf_token %}
            {% crispy form%}
          </div>
          <!-- /.card-body -->

        </form>
    </div>
</div>

{% endblock content %}

base/templates/base/laporanPik.html
{% extends 'base.html' %}
{% load static %}
{% block pageHead %}Laporan {{pik.nama}}{% endblock pageHead %}
{% block page %}Laporan {{pik.nama}}{% endblock page %}
{% block content %}
<div class="card">
    <div class="card-header">
      <h3 class="card-title">Semua PIK</h3>

      
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table id="export-ready-table" class="table-sm table table-hover bg-light table-bordered mt-3 ">
                <thead class=" table-primary table-borderless text-nowrap">
                    <tr class="text-center">
                        <th colspan="5" class="p-3 bg-light" 
                        data-f-sz="18"
                        data-a-h="center"
                        data-a-v="middle"
                        data-f-underline="true">
    
                            Laporan Kegiatan {{pik.nama}}
                        </th>
                    </tr>
                    <tr class="text-center">
    
                            <th rowspan="2" data-a-h="center"
                        data-a-v="middle" data-fill-color="65b1f0">No</th>
                            <th rowspan="2" data-a-h="center"
                        data-a-v="middle" data-fill-color="65b1f0">Judul Kegiatan</th>
                            <th rowspan="2" data-a-h="center"
                        data-a-v="middle" data-fill-color="65b1f0">Deskripsi</th>
                            <th rowspan="2" data-a-h="center"
                        data-a-v="middle" data-fill-color="65b1f0">Tanggal</th>
                            <th rowspan="2" data-a-h="center"
                        data-a-v="middle" data-fill-color="65b1f0">Dokumentasi</th>
                            
    
                        
                    </tr>
                    
                </thead>
                   
                </thead>
                <tbody class="table-table-group-divider">
                    <tr></tr>
                    {% if kegiatan.count != 0 %}
                        {% for kegiatan in kegiatan %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{kegiatan.judul}}</td>
                            <td>{{kegiatan.deskripsi | safe}}</td>
                            <td>{{kegiatan.tanggal}}</td>
                            {% if kegiatan.gambar %}
                            <td data-hyperlink="{{ request.META.HTTP_HOST }}{{kegiatan.gambar.url}}"><a target="_blank" href="{{kegiatan.gambar.url}}">{{ request.META.HTTP_HOST }}{{kegiatan.gambar.url}}</a></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    {% endif %}
                    {% comment %} {% if guest_list.count != 0 %}
                        {% for data in guest_list %}
                        <tr>
                            <td>
                                {{forloop.counter}}
                            </td>
                            <td>
                                {{data.name}}
                            </td>
                            <td data-a-h="center">
                                {% if data.email == None %}
                                -
                                {% else %}
                                {{data.email}}
                                {% endif %}
                            </td>
                            <td>
                                {{data.address}}
                            </td>
                            <td>{{data.get_gender_display}}</td>
                            <td>{{data.phone}}</td>
                            <td>{{data.needs}}</td>
                            <td>{{data.reserve_time}}</td>
                        </tr>
                        {% endfor %}
                    {% endif %} {% endcomment %}
                    
                    
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <button id="export-xls" class="btn btn-success">Cetak Laporan (Excel)</button>
        </div>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
{% endblock content %}

base/templates/base/list_anggota.html
{% extends 'base.html' %}
{% load static %}
{% block pageHead %}Anggota {{pik.nama}}{% endblock pageHead %}
{% block page %}Anggota {{pik.nama}}{% endblock page %}
{% block content %}
<div class="card">
    <div class="card-header">
      <h3 class="card-title">Daftar Anggota {{pik.nama}}</h3>

      {% comment %} <div class="card-tools">
        {% if messages %}
        {% for message in messages %}
        <p class="text-danger">{{message}}</p>
        {% endfor %}
        {% endif %}
      </div> {% endcomment %}
    </div>
    <div class="card-body p-0">
      <table class="table table-striped projects">
          <thead>
              <tr>
                  <th style="width: 1%">
                      #
                  </th>
                  <th style="width: 20%">
                      Nama
                  </th>
                  <th style="width: 30%">
                      Jenis Kelamin
                  </th >
                  <th style="width: 20%" class="text-center">
                     Jabatan
                  </th>
                  {% if request.user == pik.admin %}
                  <th style="width: 8%" class="text-center">
                      Status
                  </th>
                  {% endif %}
                 
              </tr>
          </thead>
          <tbody>
            {% for anggota in anggota %}
            <tr>
                <td>
                    {{forloop.counter}}
                </td>
                <td>
                    <a>
                        {{anggota.nama}}
                    </a>
        
                </td>
                <td>
                    <p>{{anggota.get_jenisKelamin_display}}</p>
                </td>
                <td class="project-state">
                    <span class="badge badge-success">Anggota</span>
                </td>
                {% if request.user == pik.admin %}
                <td class="project-actions text-right">
                    <a class="btn btn-info btn-sm" href="{% url 'updateAnggota' pik.id anggota.id %}">
                        <i class="fas fa-pencil-alt">
                        </i>
                        Edit
                    </a>
                    <form action="" method="post" id="delete">
                        {% csrf_token %}
                        <input type="hidden" name="delete" value="{{anggota.id}}">
                        <button type="submit" id="delete-button" class="btn btn-danger btn-sm"><i class="fas fa-trash">
                        </i> Hapus</button>
                    </form>

                </td>
                {% endif %}
                
            </tr>
            {% endfor %}
              
              
          </tbody>
      </table>
    </div>
    <!-- /.card-body -->
  </div>
{% endblock content %}

base/templates/base/list_pik.html
{% extends 'base.html' %}
{% load static %}
{% block pageHead %}List PIK{% endblock pageHead %}
{% block page %}List PIK{% endblock page %}

{% block content %}
<div class="card">
    <div class="card-header">
      <h3 class="card-title">Semua PIK</h3>

      
    </div>
    <div class="card-body p-0">
      <table class="table table-striped projects">
          <thead>
              <tr>
                  <th style="width: 1%">
                      #
                  </th>
                  <th style="width: 20%">
                      Nama PIK
                  </th>
                  <th style="width: 30%">
                      Pengurus
                  </th>
                  <th>
                      
                  </th>
                  <th style="width: 8%" class="text-center">
                      
                  </th>
                  <th style="width: 20%">
                  </th>
              </tr>
          </thead>
          <tbody>
            {% for pik in listPik %}
            <tr>
                <td>
                    {{forloop.counter}}
                </td>
                <td>
                    <a>
                        {{pik.nama}}
                    </a>
                    
                    
                </td>
                <td>
                   <a>{{pik.admin.first_name |upper}} {{pik.admin.last_name |upper}}</a>
                </td>
                <td class="project_progress">
                    
                </td>
                <td class="project-state">
                    
                </td>
                <td class="project-actions text-right">
                    <a class="btn btn-primary btn-sm" href="{% url 'detail' pik.id %}">
                        <i class="fas fa-folder">
                        </i>
                        View
                    </a>
                    {% comment %} <a class="btn btn-info btn-sm" href="#">
                        <i class="fas fa-pencil-alt">
                        </i>
                        Edit
                    </a>
                    <a class="btn btn-danger btn-sm" href="#">
                        <i class="fas fa-trash">
                        </i>
                        Delete
                    </a> {% endcomment %}
                </td>
            </tr>
            {% endfor %}
              
              
          </tbody>
      </table>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
{% endblock content %}

base/templates/base/updatePik.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block pageHead %}Update {{pik.nama}}{% endblock pageHead %}
{% block page %}Update {{pik.nama}}{% endblock page %}

{% block content %}
<div class="container-fluid">
    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Update <strong>{{pik.nama}}</strong></h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="POST">
          <div class="card-body">
            {% csrf_token %}
            {% crispy form%}
          </div>
          <!-- /.card-body -->

        </form>
    </div>
</div>
{% endblock %}